# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('storename', models.CharField(max_length=200)),
                ('store_link', models.CharField(max_length=200)),
                ('store_username', models.CharField(max_length=200)),
                ('store_pw', models.CharField(max_length=200)),
            ],
        ),
    ]
