# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelist', '0002_auto_20171118_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Electronic', 'Electronic'), ('Travel', 'Travel')], default='Food', max_length=15),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_link',
            field=models.URLField(),
        ),
    ]
